<a href="https://colab.research.google.com/github/notfirsttt/Dasar_Kecerdasan_Artifisial/blob/main/PertemuanMinggu2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Guided 1

In [ ]:
import numpy as np
x = np.array([4, 9, 2, 5])
y = np.array([3, 5, 3, 2])

k = np.concatenate((x, y))
z = x + y

print(k)
print(z)
print(z.tolist())

[4 9 2 5 3 5 3 2]
[ 7 14  5  7]
[7, 14, 5, 7]


##Guided 2


In [ ]:
import numpy as np

x = np.array([[5, 3, 2, 1], [6, 3, 2, 1]])
print("Dimensi aray x: ", x.ndim)

Dimensi aray x:  2


##Guided3

In [ ]:
import numpy as np

x = np.array([[5, 3, 2, 1], [6, 3, 2, 1]])
y = np.array([5.2, 3.3, 8.1])
print("Shape x  : ", x.shape)
print("Size x   : ", x.size)
print("Shape y  : ", y.dtype)
print("Size y   : ", y.dtype)


Shape x  :  (2, 4)
Size x   :  8
Shape y  :  float64
Size y   :  float64


##Guided 4

In [5]:
import numpy as np


x = np.zeros((3,3))
y = np.ones((2,3))
z = np.empty((2,2))
k = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)
m = np.full((2, 2), 5)
n = np.random.random((2, 3))
o = np.random.randint(0, 50, size = (2,3))


print(x)
print(y)
print(z)
print(k)
print(l)
print(m)
print(n)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.25 0.5 ]
 [0.75 1.  ]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[5 5]
 [5 5]]
[[0.77224051 0.96271273 0.00473575]
 [0.59235707 0.08086049 0.52890981]]
[[24  6 25]
 [28 22 49]]


##Guided 5

In [10]:
import numpy as np
#append pada array 1D
a = np.array([[1, 2, 3]])
a = np.append(a, [4, 5])
print("1D array setelah append:\n", a)
#append pada array 2D
x = np.array([[1, 2], [3, 4]])
x = np.append(x, [4, 5, 6])
print("2D array setelah append:\n", x)

1D array setelah append:
 [1 2 3 4 5]
2D array setelah append:
 [1 2 3 4 4 5 6]


##Guided 6

In [11]:
import numpy as np

# concatenate pada array 1D
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print("1D array setelah concatenate:\n", c)
# concatenate pada array 2D
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis=0)
print("1D array setelah concatenate:\n", z)

1D array setelah concatenate:
 [1 2 3 4]
1D array setelah concatenate:
 [[1 2]
 [3 4]
 [5 6]]


##Guided 7

In [12]:
import numpy as np

# insert pada array 1D
a = np.array([1, 2, 3])
a = np.insert(a, 1, 4) # Insert '4' pada index 1
print("1D array setelah insert:\n", a)
# insert pada array 2D
x = np.array([[1, 2], [3, 4]])
x = np.insert(x, 0, [5, 6], axis=0) # Insert baris [5, 6] index 0
print("2D array setelah insert:\n", x)

1D array setelah insert:
 [1 4 2 3]
2D array setelah insert:
 [[5 6]
 [1 2]
 [3 4]]


##Guided 8

In [14]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.delete(x, 1, axis=0)
print(x)

[[1 2 3]
 [7 8 9]]


##Guided 9

In [15]:
import numpy as np

x = np.array([4, 2, 7])
y = np.sort(x)
print("Array yang telah diurutkan:", y)

Array yang telah diurutkan: [2 4 7]


##Guided 10

In [17]:
import numpy as np

x = np.array([[3, 2, 4], [1, 4, 5]])
y = np.sort(x, axis=0) # Mengurutkan sepanjang kolom
print("Array yang telah diurutkan sepanjang kolom:\n", y)

z = np.sort(x) # Mengurutkan sepanjang baris
print("Array yang telah diurutkan sepanjang baris:\n", z)

Array yang telah diurutkan sepanjang kolom:
 [[1 2 4]
 [3 4 5]]
Array yang telah diurutkan sepanjang baris:
 [[2 3 4]
 [1 4 5]]


##Guided 11

In [20]:
import numpy as np

x = np.array([20, 80, 10, 50, 30])
subset = x[1:4]

#indexing
print(x[2])

print(subset)

10
[80 10 50]


##Guided 12

In [22]:
import numpy as np

x = np.array([3, 2, 6, 5])
# Membuat shallow copy menggunakan view()
y = x.view()
# Mengubah elemen pertama dari shallow copy
y[0] = 99
print("Array asli:", x)
print("Shallow copy:", y)

Array asli: [99  2  6  5]
Shallow copy: [99  2  6  5]


##Guided 13

In [24]:
import numpy as np

x = np.array([3, 2, 6, 5])

y = x.copy()
y[0] = 99

print("Array asli:", x)
print("Deep copy:", y)

Array asli: [3 2 6 5]
Deep copy: [99  2  6  5]


##Guided 14

In [29]:
import numpy as np

x = np.array ([7, 2, 9, 3])

#Nilai Maksimal
max_value = np.max(x)
print("Nilai maks : ", max_value)

#Nilai Minimum
min_value = np.min(x)
print("Nilai min : ", min_value)

#Penjumlahan
sum_value = np.sum(x)
print("Jumlah : ", sum_value)

#Rata-rata
mean_value = np.mean(x)
print("Rata-rata : ", mean_value)

Nilai maks :  9
Nilai min :  2
Jumlah :  21
Rata-rata :  5.25


##Unguided 1

##Unguided 2